import ast
import json
import re
import string
from pathlib import Path

import pytest

from easy_ci import i18n

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "easy_ci"
TRANSLATION_FUNCTIONS = {"tr", "N_", "plural"}


def python_messages() -> set[str]:
    """Tous les textes passés littéralement à tr(), N_() ou plural() dans le moteur."""
    messages: set[str] = set()
    for path in PACKAGE.rglob("*.py"):
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in TRANSLATION_FUNCTIONS:
                args = node.args[1:3] if node.func.id == "plural" else node.args[:1]
                # Un argument non littéral est une constante déjà marquée par N_() ailleurs.
                messages.update(arg.value for arg in args if isinstance(arg, ast.Constant) and isinstance(arg.value, str))
    return messages


def placeholders(text: str) -> set[str]:
    return {name.split("!")[0].split(":")[0] for _, name, _, _ in string.Formatter().parse(text) if name}


@pytest.mark.parametrize("language", [lang for lang in i18n.LANGUAGES if lang != i18n.SOURCE_LANGUAGE])
def test_python_catalog_is_complete(language):
    catalog = json.loads((PACKAGE / "locales" / f"{language}.json").read_text(encoding="utf-8"))
    messages = python_messages()
    missing = sorted(messages - catalog.keys())
    assert not missing, f"Traductions manquantes ({language}) :\n" + "\n".join(missing)
    stale = sorted(catalog.keys() - messages)
    assert not stale, f"Traductions inutilisées ({language}) :\n" + "\n".join(stale)
    for source, translated in catalog.items():
        assert translated.strip(), f"Traduction vide : {source!r}"
        assert placeholders(source) == placeholders(translated), f"Variables différentes : {source!r} → {translated!r}"


def test_tr_and_plural_follow_language():
    try:
        i18n.set_language("en")
        assert i18n.tr("Saisissez un titre.") == "Enter a title."
        assert i18n.tr("Texte absent du catalogue") == "Texte absent du catalogue"
        i18n.set_language("fr-FR")
        assert i18n.current_language() == "fr"
        assert i18n.tr("Aucun compte {provider_name} connecté.", provider_name="GitLab") == "Aucun compte GitLab connecté."
        i18n.set_language("de")  # langue non disponible : inchangée
        assert i18n.current_language() == "fr"
    finally:
        i18n.set_language("fr")


def test_normalize_and_system_language(monkeypatch):
    assert i18n.normalize("en_US.UTF-8") == "en" and i18n.normalize("fr-CA") == "fr" and i18n.normalize("es") is None
    assert i18n.system_language() in i18n.LANGUAGES


def test_api_messages_follow_request_language(tmp_path):
    from easy_ci.api import Api
    from easy_ci.storage import SettingsStore

    class NoCredentials:
        def load(self, provider):
            return None

        def save(self, provider, credentials):
            return True

        def clear(self, provider):
            pass

    api = Api(NoCredentials(), SettingsStore(tmp_path / "s.json"))
    try:
        assert api.call("list_runs", {"provider": "gitlab", "full_name": "a/b"}, "en")["error"]["message"] == "No GitLab account connected."
        assert api.call("list_runs", {"provider": "gitlab", "full_name": "a/b"}, "fr")["error"]["message"] == "Aucun compte GitLab connecté."
        api.call("start_demo", None, "en")
        repos = api.call("list_repositories", {"provider": "github"}, "en")["data"]
        assert any(repo["description"] == "Team internal documentation" for repo in repos)
        generated = api.call("generate_pipeline", {"key": "github:acme/handbook", "options": api.call("detect_project", {"key": "github:acme/handbook"}, "en")["data"]["options"]}, "en")["data"]
        assert generated["content"].startswith("# Pipeline generated by Easy CI") and generated["validation"]["valid"]
    finally:
        i18n.set_language("fr")


def test_no_untranslated_french_in_python():
    """Aucun texte visible en français hors tr()/N_() (docstrings, logs et outils de développement exclus)."""
    french = re.compile(r"[éèêàùâîôûçÉÈÀ«»]")
    excluded = {"__main__.py", "devserver.py", "i18n.py", "selfcheck.py", "demo_projects.py"}
    offenders = []
    for path in PACKAGE.rglob("*.py"):
        if path.name in excluded:
            continue
        tree = ast.parse(path.read_text(encoding="utf-8"))
        parents = {child: parent for parent in ast.walk(tree) for child in ast.iter_child_nodes(parent)}

        def exempt(node, parents=parents):
            parent = parents.get(node)
            if isinstance(parent, ast.Expr) or (isinstance(parent, ast.Dict) and node in parent.keys):
                return True
            while node in parents:
                node = parents[node]
                if isinstance(node, ast.Call):
                    func = node.func
                    if isinstance(func, ast.Name) and func.id in TRANSLATION_FUNCTIONS | {"print"}:
                        return True
                    if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name) and func.value.id in ("log", "logger"):
                        return True
            return False

        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, str) and not isinstance(parents.get(node), ast.JoinedStr):
                text = node.value
            elif isinstance(node, ast.JoinedStr):
                text = "".join(part.value for part in node.values if isinstance(part, ast.Constant))
            else:
                continue
            if french.search(text) and not exempt(node):
                offenders.append(f"{path.relative_to(ROOT)}:{node.lineno}: {text[:80]!r}")
    assert not offenders, "\n".join(offenders)
